name: Python Package using Conda

on: [push] 

jobs:
  build:
    runs-on: rpi-sense
    strategy:
      matrix:
        python-version: ['3.x']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install labpack
      - run: pip install RPi.GPIO
      - run: pip3 install google-api-python-client
      - run: python main.py
